# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openvla.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'openvla.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ropenvla.proto\x12\x07openvla\"d\n\x10\x41ttentionRequest\x12\x0e\n\x06\x66rames\x18\x01 \x03(\x0c\x12\x13\n\x0binstruction\x18\x02 \x01(\t\x12\x15\n\rlayer_indices\x18\x03 \x03(\x05\x12\x14\n\x0chead_indices\x18\x04 \x03(\x05\"\x81\x02\n\x11\x41ttentionResponse\x12\x45\n\x0e\x61ttention_maps\x18\x01 \x03(\x0b\x32-.openvla.AttentionResponse.AttentionMapsEntry\x12=\n\nshape_info\x18\x02 \x03(\x0b\x32).openvla.AttentionResponse.ShapeInfoEntry\x1a\x34\n\x12\x41ttentionMapsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x1a\x30\n\x0eShapeInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x0f\n\rHealthRequest\"7\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x14\n\x0cmodel_loaded\x18\x02 \x01(\x08\x32\x92\x01\n\x0eOpenVLAService\x12\x45\n\x0cGetAttention\x12\x19.openvla.AttentionRequest\x1a\x1a.openvla.AttentionResponse\x12\x39\n\x06Health\x12\x16.openvla.HealthRequest\x1a\x17.openvla.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openvla_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATTENTIONRESPONSE_ATTENTIONMAPSENTRY']._loaded_options = None
  _globals['_ATTENTIONRESPONSE_ATTENTIONMAPSENTRY']._serialized_options = b'8\001'
  _globals['_ATTENTIONRESPONSE_SHAPEINFOENTRY']._loaded_options = None
  _globals['_ATTENTIONRESPONSE_SHAPEINFOENTRY']._serialized_options = b'8\001'
  _globals['_ATTENTIONREQUEST']._serialized_start=26
  _globals['_ATTENTIONREQUEST']._serialized_end=126
  _globals['_ATTENTIONRESPONSE']._serialized_start=129
  _globals['_ATTENTIONRESPONSE']._serialized_end=386
  _globals['_ATTENTIONRESPONSE_ATTENTIONMAPSENTRY']._serialized_start=284
  _globals['_ATTENTIONRESPONSE_ATTENTIONMAPSENTRY']._serialized_end=336
  _globals['_ATTENTIONRESPONSE_SHAPEINFOENTRY']._serialized_start=338
  _globals['_ATTENTIONRESPONSE_SHAPEINFOENTRY']._serialized_end=386
  _globals['_HEALTHREQUEST']._serialized_start=388
  _globals['_HEALTHREQUEST']._serialized_end=403
  _globals['_HEALTHRESPONSE']._serialized_start=405
  _globals['_HEALTHRESPONSE']._serialized_end=460
  _globals['_OPENVLASERVICE']._serialized_start=463
  _globals['_OPENVLASERVICE']._serialized_end=609
# @@protoc_insertion_point(module_scope)
