# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import openvla_pb2 as openvla__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in openvla_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OpenVLAServiceStub(object):
    """OpenVLA-7B gRPC 서비스
    Phase 1 probing: GetAttention RPC
    Phase 2 이후: Infer RPC (success_score 필드 추가 예정)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAttention = channel.unary_unary(
                '/openvla.OpenVLAService/GetAttention',
                request_serializer=openvla__pb2.AttentionRequest.SerializeToString,
                response_deserializer=openvla__pb2.AttentionResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/openvla.OpenVLAService/Health',
                request_serializer=openvla__pb2.HealthRequest.SerializeToString,
                response_deserializer=openvla__pb2.HealthResponse.FromString,
                _registered_method=True)


class OpenVLAServiceServicer(object):
    """OpenVLA-7B gRPC 서비스
    Phase 1 probing: GetAttention RPC
    Phase 2 이후: Infer RPC (success_score 필드 추가 예정)
    """

    def GetAttention(self, request, context):
        """Phase 1 전용: attention map 추출
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """서버 / 모델 로드 상태 확인
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenVLAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAttention': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttention,
                    request_deserializer=openvla__pb2.AttentionRequest.FromString,
                    response_serializer=openvla__pb2.AttentionResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=openvla__pb2.HealthRequest.FromString,
                    response_serializer=openvla__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openvla.OpenVLAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openvla.OpenVLAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpenVLAService(object):
    """OpenVLA-7B gRPC 서비스
    Phase 1 probing: GetAttention RPC
    Phase 2 이후: Infer RPC (success_score 필드 추가 예정)
    """

    @staticmethod
    def GetAttention(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openvla.OpenVLAService/GetAttention',
            openvla__pb2.AttentionRequest.SerializeToString,
            openvla__pb2.AttentionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openvla.OpenVLAService/Health',
            openvla__pb2.HealthRequest.SerializeToString,
            openvla__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
